Task 4
charlotte-praktikum-team/praktikum-game pull request #36
Opened 2022-08-10 18:33 UTC by elaineir

## Связанная задача: [4](https://github.com/charlotte-praktikum-team/praktikum-game/issues/4)

### Описание выполненной работы:
- Сверстан шаблон страницы авторизации
- Сверстана форма авторизации
- Сверстана страница логина
- Подключен `formik` и `yup` для управления формами и валидации
- Обновлены компоненты Input, Link, Heading
- Исправлены стили для контента

Кнопку для авторизации через Яндекс добавлю позже, в 7 спринте.

![Login Page](https://user-images.githubusercontent.com/75016726/183989121-0265656f-f7fa-45e9-a132-010902475fa4.jpg)

2022-08-10 18:53 UTC, mihalichpalich requested changes, later dismissed

2022-08-10 18:53 UTC, mihalichpalich commented on src/router/router.tsx
> +import Login from '@/pages/login/login';
Подключение страниц лучше делать через lazy

2022-08-10 18:53 UTC, mihalichpalich commented on src/router/router.tsx
> +      <Route path={routes.login.path} element={<Login />} />
И саму страницу обернуть с Suspense для передачи в роут

2022-08-10 19:01 UTC, elaineir commented on src/router/router.tsx
> +      <Route path={routes.login.path} element={<Login />} />
Suspense есть на App, есть смысл делать ещё одну обертку?

2022-08-10 19:20 UTC, Mickilol commented on src/router/router.tsx
> +      <Route path={routes.login.path} element={<Login />} />
Мне кажется, что обертки в app достаточно, так как выполняется одна и та же функция

2022-08-10 19:43 UTC, Mickilol commented on src/components/input/input.css
> +  &__input:focus + .field__label,
А зачем тут явное название класса-обертки?

2022-08-10 19:43 UTC, Mickilol commented on src/components/input/types.ts
> +type InputTypes = 'text' | 'password' | 'tel' | 'email';
Тип alias здесь подразумевает наличие одного из этих значений, поэтому лучше назвать его в единственном числе

2022-08-10 19:53 UTC, elaineir commented on src/components/input/input.css
> +  &__input:focus + .field__label,
stylelint воюет с преттиером, преттиер портит путь, а stylelint не стал запускать сборку...

2022-08-10 21:10 UTC, elaineir commented
Исправила все замечания

2022-08-11 07:25 UTC, mihalichpalich approved these changes

2022-08-11 10:09 UTC, Mickilol approved these changes

2022-08-11 10:38 UTC, Pavlicheck approved these changes

2022-08-11 11:04 UTC, merged